app/models.py
# app/models.py

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager

class Employee(UserMixin, db.Model):
    """
    Create Employee table
    """

    # Ensures table will be named in plural and not in singular 
    # as in the name of the model
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    emp_number = db.Column(db.String(10), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    emp_name = db.Column(db.String(100), index=True)
    password_hash = db.Column(db.String(128))
    subproject_id = db.Column(db.Integer, db.ForeignKey('projects.id'))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    is_admin = db.Column(db.Boolean, default=False)
    attendances = db.relationship('Attendance', backref='employee', 
                                    lazy='dynamic')
    incentives = db.relationship('Incentive', backref='employee', 
                                    lazy='dynamic')
    

    @property
    def password(self):
        """
        Prevent password from being accessed
        """
        raise AttributeError('Password is not readable.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Employee: {}>'.format(self.username)

# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return Employee.query.get(int(user_id))

class Role(db.Model):
    """
    Create a Role table
    """

    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    employees = db.relationship('Employee', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role: {}>'.format(self.name)
        
class Project(db.Model):
    """
    Create a Project table
    """

    __tablename__ = 'projects'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'))
    description = db.Column(db.String(200))
    subprojects = db.relationship('Subproject', backref='project', 
                                    lazy='dynamic')
                                    
class Subproject(db.Model):
    """
    Create a Subproject class
    """

    __tablename__ = 'subprojects'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'))
    employees = db.relationship('Employee', backref='subproject', lazy='dynamic')
    incentives = db.relationship('Incentive', backref='subproject', lazy='dynamic')

    def __repr__(self):
        return '<Subproject: {}>'.format(self.name)
        
class Attendance(db.Model):
    """
    Create an Attendance class
    """

    __tablename__ = 'attendances'

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'))
    leave_days = db.Column(db.Integer)
    days_present = db.Column(db.Integer)
    percentage_attendance = db.Column(db.Integer)
    incentives = db.relationship('Incentive', backref='attendance', lazy='dynamic')
    
class Incentive(db.Model):
    """
    Create an Incentive table
    """

    __tablename__ = 'incentives'

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'))
    subproject_id = db.Column(db.Integer, db.ForeignKey('subprojects.id'))
    attendances_id = db.Column(db.Integer, db.ForeignKey('attendances.id'))
    production = db.Column(db.Integer)
    av_qa_score = db.Column(db.Integer)
    total_points = db.Column(db.Integer)
    amount = db.Column(db.Float)

app/admin/forms.py
# app/admin/forms.py

app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate

# local imports
from config import app_config

# db_variable initialization
db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page"
    login_manager.login_view = "auth.login"

    migrate = Migrate(app, db)

    from app import models

    return app

app/admin/__init__.py
# app/admin/__init__.py

from flask import Blueprint

admin = Blueprint('admin', __name__)
 
from . import views

app/admin/views.py
# app/admin/views.py

app/attendance/__init__.py
# app/attendance/__init__.py

from flask import Blueprint

attendance = Blueprint('attendance', __name__)

from . import views

app/employee/__init__.py
# app/employee/__init__.py

from flask import Blueprint

employee = Blueprint('employee', __name__)

from . import views

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template
from flask_login import login_required

from . import home

@home.route('/')
def homepage():
    """
    Render the home template on the / route
    """
    return render_template('home/index.html', title="Home")
    
@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

app/incentive/__init__.py
# app/incentive/__init__.py

from flask import Blueprint

incentive = Blueprint('incentive', __name__)

from . import views

app/project/__init__.py
# app/project/__init__.py

from flask import Blueprint

project = Blueprint('project', __name__)

from . import views

app/role/__init__.py
# app/role/__init__.py

from flask import Blueprint

role = Blueprint('role', __name__)

from . import views

#.

app/subproject/__init__.py
# app/subproject/__init__.py

from flask import Blueprint

subproject = Blueprint('subproject', __name__)

from . import views

app/templates/base.html
<!-- app/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Masa Course Incentive</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Masa Course Incentive</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                  <li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
                  <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    </ul>
                    <p class="copyright text-muted small">Masa Course Incentive Copyright © 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>The Dashboard</h1>
                    <h3>We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Masa Course Incentive</h1>
                    <h3>The Incentive Programme Automated!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}